/* js/music-player.js - singleton audio + renderMusicLibrary */
(function(){
  function getMusicAudio(){ let a=document.getElementById('music-playing-audio'); if(a) return a; document.querySelectorAll('audio').forEach(el=>{ if(el.id!=='music-playing-audio') try{ el.pause(); el.remove(); }catch(e){} }); a=document.createElement('audio'); a.id='music-playing-audio'; a.preload='metadata'; a.crossOrigin='anonymous'; a.style.display='none'; document.body.appendChild(a); a.addEventListener('error', ()=> showMusicError('Erro ao reproduzir a faixa.')); a.addEventListener('playing', ()=> clearMusicError()); return a; }
  let musicLoadTimeout = null;
  function playMusicUrl(url){ if(!url) return; const audio=getMusicAudio(); try{ audio.pause(); }catch(e){} audio.src=url; audio.load(); musicLoadTimeout && clearTimeout(musicLoadTimeout); musicLoadTimeout=setTimeout(()=>{ if(audio.readyState<3 && !audio.paused) showMusicError('Tempo de carregamento excedido.'); },15000); audio.play().catch(err=>{ console.warn(err); showMusicError('Clique para tentar reproduzir a música.'); }); audio.addEventListener('playing', function _on(){ clearMusicError(); musicLoadTimeout && clearTimeout(musicLoadTimeout); audio.removeEventListener('playing', _on); }); }
  function showMusicError(msg){ let el=document.getElementById('music-error-container'); if(!el){ el=document.createElement('div'); el.id='music-error-container'; Object.assign(el.style,{position:'fixed',bottom:'12px',left:'50%',transform:'translateX(-50%)',background:'rgba(0,0,0,0.8)',color:'#fff',padding:'8px 12px',borderRadius:'6px',zIndex:100000}); document.body.appendChild(el);} el.textContent=msg; }
  function clearMusicError(){ const el=document.getElementById('music-error-container'); if(el) el.remove(); musicLoadTimeout && clearTimeout(musicLoadTimeout); musicLoadTimeout=null; }

  window.renderMusicLibrary = function(m){ const grid=document.getElementById('music-grid'); if(!grid) return; grid.innerHTML=''; (m.themes||[]).forEach(t=>{ const c=document.createElement('div'); c.className='music-card'; c.innerHTML=`<img src="${t.cover||'images/bg-default.jpg'}" style="width:64px;height:64px;object-fit:cover;"><div class="music-info"><strong>${t.title}</strong><div>${t.artist} • ${t.anime}</div></div><button class="play-music" data-audio="${t.audio}">▶</button>`; grid.appendChild(c); }); grid.querySelectorAll('.play-music').forEach(b=>b.addEventListener('click', ()=> playMusicUrl(b.dataset.audio))); };
  document.addEventListener('DOMContentLoaded', ()=>{ window.addEventListener('animeDataLoaded', ()=>{ try{ if(window.animeDB && window.animeDB.musicLibrary) renderMusicLibrary(window.animeDB.musicLibrary); }catch(e){} }); });
  window.playMusicUrl = playMusicUrl;
})();
